import sys

# Keyboard mapping macros
LINE_BEGIN_KEY = 1
LINE_END_KEY = 5
TAB_KEY = 9
NEWLINE_KEY = 13
ESC_CODE = 224  # 27?
BACK_SPACE_KEY = 8

ARROW_UP_KEY = 72
ARROW_DOWN_KEY = 80
ARROW_LEFT_KEY = 75
ARROW_RIGHT_KEY = 77
HOME_KEY = 71
END_KEY = 79
PG_UP_KEY = 73
PG_DOWN_KEY = 81
DELETE_KEY = 83

UNDEFINED_KEY = sys.maxsize
BEEP_CHAR = 7
BACK_SPACE_CHAR = 8
SPACE_CHAR = 32
INTERRUPT_KEY = 3